let basepath = ""
const imgslist = {
    "Apprentice" : basepath + "Heroico/app.png",
    "Squire" : basepath + "Heroico/squ.png",
    "Huntress" : basepath + "Heroico/hun.png",
    "Monk" : basepath + "Heroico/mon.png",
    "Abyss Lord" : basepath + "Heroico/aby.png",
    "Series EV2" : basepath + "Heroico/ev2.png",
    "Gunwitch" : basepath + "Heroico/gun.png",
    "Lavamancer" : basepath + "Heroico/lav.png",
    "Mystic" : basepath + "Heroico/mys.png",
    "Dryad" : basepath + "Heroico/dry.png",
    "Initiate" : basepath + "Heroico/ini.png",
    "Adept" : basepath + "Heroico/ade.png",
    "Barbarian" : basepath + "Heroico/bar.png",
    "Mercenary" : basepath + "Heroico/mer.png",
    "Countess" : basepath + "Heroico/cou.png",
    "GreenShard":"Shard/GreenShard.png",
    "Totem":"Mod/TotemIcon.png",
    "Medal":"Mod/medallion.png",
    "MOD10":"Mod/MOD10.png",
    "C0":"Shard/C0.png",
    "C1":"Shard/C1.png",
    "C2":"Shard/C2.png",
    "C3":"Shard/C3.png",
    "C4":"Shard/C4.png",
    "C5":"Shard/C5.png",
    "C6":"Shard/C6.png",
    "C7":"Shard/C7.png",
    "C8":"Shard/C8.png",
    "C9":"Shard/C9.png",
    "C10":"Shard/C10.png",
    "Mastery":"Shard/Mastery.png",
    "1":"Tower/1.png",
    "2":"Tower/2.png",
    "3":"Tower/3.png",
    "4":"Tower/4.png",
}
export default imgslist;