let basepath = ""
const imgslist = {
    "Apprentice" : basepath + "Heroico/app.png",
    "Squire" : basepath + "Heroico/squ.png",
    "Huntress" : basepath + "Heroico/hun.png",
    "Monk" : basepath + "Heroico/mon.png",
    "Abyss Lord" : basepath + "Heroico/aby.png",
    "Series EV2" : basepath + "Heroico/ev2.png",
    "Gunwitch" : basepath + "Heroico/gun.png",
    "Lavamancer" : basepath + "Heroico/lav.png",
    "Mystic" : basepath + "Heroico/mys.png",
    "Dryad" : basepath + "Heroico/dry.png",
    "Initiate" : basepath + "Heroico/ini.png",
    "Adept" : basepath + "Heroico/ade.png",
    "Barbarian" : basepath + "Heroico/bar.png",
    "Mercenary" : basepath + "Heroico/mer.png",
    "Countess" : basepath + "Heroico/cou.png",
    "GreenShard":"Shard/GreenShard.png",
    "Totem":"Mod/TotemIcon.png",
    "Medal":"Mod/medallion.png",
    "1":"Tower/1.png",
    "2":"Tower/2.png",
    "3":"Tower/3.png",
    "4":"Tower/4.png",
}
export default imgslist;